name: Revurb
favicon: null
layout_spectrum: 0.08807
typography_spectrum: 0.58943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0d7d0'
    - '#bec9c1'
    - '#adb9af'
    - '#8d9e98'
    - '#828684'
  brandStrength: 0.1875
  lightness: 0.125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
